<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KCVLOK6" failures="1" tests="8" name="Default test" time="0.433" errors="0" timestamp="24 Mar 2022 15:52:06 GMT">
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add1Test" time="0.084"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add3Test" time="0.018"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add2Test" time="0.008">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;11&amp;gt; but was:&amp;lt;9&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<11> but was:<9>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:277)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:195)
	at junit.framework.Assert.assertEquals(Assert.java:201)
	at examplePackageForTestNg.CalculatorTest2.add2Test(CalculatorTest2.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- add2Test -->
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="sub1Test" time="0.027"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="sub2Test" time="0.008"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="mul1Test" time="0.014"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="devideByZeroTest" time="0.014"/>
  <testcase classname="examplePackageForTestNg.CalculatorTest2" name="add4Test" time="0.008">
    <skipped/>
  </testcase> <!-- add4Test -->
</testsuite> <!-- Default test -->
